main:
	javac **/*.java --module-path "../lib/javafx" --add-modules javafx.controls,javafx.fxml

run:
	java --module-path "../lib/javafx" --add-modules javafx.controls,javafx.fxml View.HelloFx

clear:
	rm **/*.class
